### ISSUE TITLE
Pretrained COCO models 

### ISSUE THREAD

**Issue by runopti** [microsoft/robust-models-transfer#10]
It looks like pretrained models on COCO are still missing? Any chance you could upload the weights?

**Comment by lengstrom** [comment]
We have uploaded the model checkpoint directories in this dropbox folder:

https://www.dropbox.com/sh/91cmipkj4zrhlgd/AAA1ZFRl2KyrW4xuABvtCOoia

The logs folder for each checkpoint directory correspond to the following naming scheme: `<task>/<pretrained model>`. The `<pretrained model>` subpart of the file path will contain an epsilon if corresponding to a robustly trained model. All the tasks correspond to COCO (object detection or instance segmentation) save `tfer_objdet_voc`. 

These checkpoint directories were generated using the Detectron2 standard training script: `https://github.com/facebookresearch/detectron2/blob/main/tools/train_net.py`. The only arguments we passed consisted of GPU settings (i.e. number of GPUs) and the path to the config file (which can be found in the checkpoint directories underneath `<checkpoint directory>/config.yaml`). 

If you want to replicate the config file exactly you will need to modify the config files to point to paths on your system; the `MODEL/WEIGHTS` parameter should point to the `detectron2_weights.pkl` file in the same directory (I would recommend using absolute paths here because Detectron2 can have strange behavior with relative paths). The `_BASE_` parameter should be renamed to correspond to the standard config file with the same basename found here: `https://github.com/facebookresearch/detectron2/tree/main/configs`. The `OUTPUT_DIR` directory should also be renamed to point to another directory on your system.

Let me know if you need any additional help.

**Comment by runopti** [comment]
Thank you for the models and detailed description!
